export interface Character {
  char: string;
  reading: string;
  category: "hiragana" | "katakana" | "alphabet";
}

export const hiraganaData: Character[] = [
  { char: "あ", reading: "あ", category: "hiragana" },
  { char: "い", reading: "い", category: "hiragana" },
  { char: "う", reading: "う", category: "hiragana" },
  { char: "え", reading: "え", category: "hiragana" },
  { char: "お", reading: "お", category: "hiragana" },
  { char: "か", reading: "か", category: "hiragana" },
  { char: "き", reading: "き", category: "hiragana" },
  { char: "く", reading: "く", category: "hiragana" },
  { char: "け", reading: "け", category: "hiragana" },
  { char: "こ", reading: "こ", category: "hiragana" },
  { char: "さ", reading: "さ", category: "hiragana" },
  { char: "し", reading: "し", category: "hiragana" },
  { char: "す", reading: "す", category: "hiragana" },
  { char: "せ", reading: "せ", category: "hiragana" },
  { char: "そ", reading: "そ", category: "hiragana" },
  { char: "た", reading: "た", category: "hiragana" },
  { char: "ち", reading: "ち", category: "hiragana" },
  { char: "つ", reading: "つ", category: "hiragana" },
  { char: "て", reading: "て", category: "hiragana" },
  { char: "と", reading: "と", category: "hiragana" },
  { char: "な", reading: "な", category: "hiragana" },
  { char: "に", reading: "に", category: "hiragana" },
  { char: "ぬ", reading: "ぬ", category: "hiragana" },
  { char: "ね", reading: "ね", category: "hiragana" },
  { char: "の", reading: "の", category: "hiragana" },
  { char: "は", reading: "は", category: "hiragana" },
  { char: "ひ", reading: "ひ", category: "hiragana" },
  { char: "ふ", reading: "ふ", category: "hiragana" },
  { char: "へ", reading: "へ", category: "hiragana" },
  { char: "ほ", reading: "ほ", category: "hiragana" },
  { char: "ま", reading: "ま", category: "hiragana" },
  { char: "み", reading: "み", category: "hiragana" },
  { char: "む", reading: "む", category: "hiragana" },
  { char: "め", reading: "め", category: "hiragana" },
  { char: "も", reading: "も", category: "hiragana" },
  { char: "や", reading: "や", category: "hiragana" },
  { char: "ゆ", reading: "ゆ", category: "hiragana" },
  { char: "よ", reading: "よ", category: "hiragana" },
  { char: "ら", reading: "ら", category: "hiragana" },
  { char: "り", reading: "り", category: "hiragana" },
  { char: "る", reading: "る", category: "hiragana" },
  { char: "れ", reading: "れ", category: "hiragana" },
  { char: "ろ", reading: "ろ", category: "hiragana" },
  { char: "わ", reading: "わ", category: "hiragana" },
  { char: "を", reading: "を", category: "hiragana" },
  { char: "ん", reading: "ん", category: "hiragana" },
];

export const katakanaData: Character[] = [
  { char: "ア", reading: "ア", category: "katakana" },
  { char: "イ", reading: "イ", category: "katakana" },
  { char: "ウ", reading: "ウ", category: "katakana" },
  { char: "エ", reading: "エ", category: "katakana" },
  { char: "オ", reading: "オ", category: "katakana" },
  { char: "カ", reading: "カ", category: "katakana" },
  { char: "キ", reading: "キ", category: "katakana" },
  { char: "ク", reading: "ク", category: "katakana" },
  { char: "ケ", reading: "ケ", category: "katakana" },
  { char: "コ", reading: "コ", category: "katakana" },
  { char: "サ", reading: "サ", category: "katakana" },
  { char: "シ", reading: "シ", category: "katakana" },
  { char: "ス", reading: "ス", category: "katakana" },
  { char: "セ", reading: "セ", category: "katakana" },
  { char: "ソ", reading: "ソ", category: "katakana" },
  { char: "タ", reading: "タ", category: "katakana" },
  { char: "チ", reading: "チ", category: "katakana" },
  { char: "ツ", reading: "ツ", category: "katakana" },
  { char: "テ", reading: "テ", category: "katakana" },
  { char: "ト", reading: "ト", category: "katakana" },
  { char: "ナ", reading: "ナ", category: "katakana" },
  { char: "ニ", reading: "ニ", category: "katakana" },
  { char: "ヌ", reading: "ヌ", category: "katakana" },
  { char: "ネ", reading: "ネ", category: "katakana" },
  { char: "ノ", reading: "ノ", category: "katakana" },
  { char: "ハ", reading: "ハ", category: "katakana" },
  { char: "ヒ", reading: "ヒ", category: "katakana" },
  { char: "フ", reading: "フ", category: "katakana" },
  { char: "ヘ", reading: "ヘ", category: "katakana" },
  { char: "ホ", reading: "ホ", category: "katakana" },
  { char: "マ", reading: "マ", category: "katakana" },
  { char: "ミ", reading: "ミ", category: "katakana" },
  { char: "ム", reading: "ム", category: "katakana" },
  { char: "メ", reading: "メ", category: "katakana" },
  { char: "モ", reading: "モ", category: "katakana" },
  { char: "ヤ", reading: "ヤ", category: "katakana" },
  { char: "ユ", reading: "ユ", category: "katakana" },
  { char: "ヨ", reading: "ヨ", category: "katakana" },
  { char: "ラ", reading: "ラ", category: "katakana" },
  { char: "リ", reading: "リ", category: "katakana" },
  { char: "ル", reading: "ル", category: "katakana" },
  { char: "レ", reading: "レ", category: "katakana" },
  { char: "ロ", reading: "ロ", category: "katakana" },
  { char: "ワ", reading: "ワ", category: "katakana" },
  { char: "ヲ", reading: "ヲ", category: "katakana" },
  { char: "ン", reading: "ン", category: "katakana" },
];

export const alphabetData: Character[] = [
  { char: "A", reading: "エー", category: "alphabet" },
  { char: "B", reading: "ビー", category: "alphabet" },
  { char: "C", reading: "シー", category: "alphabet" },
  { char: "D", reading: "ディー", category: "alphabet" },
  { char: "E", reading: "イー", category: "alphabet" },
  { char: "F", reading: "エフ", category: "alphabet" },
  { char: "G", reading: "ジー", category: "alphabet" },
  { char: "H", reading: "エイチ", category: "alphabet" },
  { char: "I", reading: "アイ", category: "alphabet" },
  { char: "J", reading: "ジェー", category: "alphabet" },
  { char: "K", reading: "ケー", category: "alphabet" },
  { char: "L", reading: "エル", category: "alphabet" },
  { char: "M", reading: "エム", category: "alphabet" },
  { char: "N", reading: "エヌ", category: "alphabet" },
  { char: "O", reading: "オー", category: "alphabet" },
  { char: "P", reading: "ピー", category: "alphabet" },
  { char: "Q", reading: "キュー", category: "alphabet" },
  { char: "R", reading: "アール", category: "alphabet" },
  { char: "S", reading: "エス", category: "alphabet" },
  { char: "T", reading: "ティー", category: "alphabet" },
  { char: "U", reading: "ユー", category: "alphabet" },
  { char: "V", reading: "ブイ", category: "alphabet" },
  { char: "W", reading: "ダブリュー", category: "alphabet" },
  { char: "X", reading: "エックス", category: "alphabet" },
  { char: "Y", reading: "ワイ", category: "alphabet" },
  { char: "Z", reading: "ゼット", category: "alphabet" },
  { char: "a", reading: "えー", category: "alphabet" },
  { char: "b", reading: "びー", category: "alphabet" },
  { char: "c", reading: "しー", category: "alphabet" },
  { char: "d", reading: "でぃー", category: "alphabet" },
  { char: "e", reading: "いー", category: "alphabet" },
  { char: "f", reading: "えふ", category: "alphabet" },
  { char: "g", reading: "じー", category: "alphabet" },
  { char: "h", reading: "えいち", category: "alphabet" },
  { char: "i", reading: "あい", category: "alphabet" },
  { char: "j", reading: "じぇー", category: "alphabet" },
  { char: "k", reading: "けー", category: "alphabet" },
  { char: "l", reading: "える", category: "alphabet" },
  { char: "m", reading: "えむ", category: "alphabet" },
  { char: "n", reading: "えぬ", category: "alphabet" },
  { char: "o", reading: "おー", category: "alphabet" },
  { char: "p", reading: "ぴー", category: "alphabet" },
  { char: "q", reading: "きゅー", category: "alphabet" },
  { char: "r", reading: "あーる", category: "alphabet" },
  { char: "s", reading: "えす", category: "alphabet" },
  { char: "t", reading: "てぃー", category: "alphabet" },
  { char: "u", reading: "ゆー", category: "alphabet" },
  { char: "v", reading: "ぶい", category: "alphabet" },
  { char: "w", reading: "だぶりゅー", category: "alphabet" },
  { char: "x", reading: "えっくす", category: "alphabet" },
  { char: "y", reading: "わい", category: "alphabet" },
  { char: "z", reading: "ぜっと", category: "alphabet" },
];

export const getCharacterData = (
  category: "hiragana" | "katakana" | "alphabet"
): Character[] => {
  switch (category) {
    case "hiragana":
      return hiraganaData;
    case "katakana":
      return katakanaData;
    case "alphabet":
      return alphabetData;
    default:
      return [];
  }
};
